import { StyleSheet } from 'react-native';

/** Shared dark styling for the login/register screens (Claude Design variant "1a"). */
export const authStyles = StyleSheet.create({
  screen: { backgroundColor: '#17161a' },
  scroll: { flexGrow: 1, paddingBottom: 40 },
  body: { paddingHorizontal: 26, marginTop: -26 },
  h1: { fontFamily: 'Caprasimo_400Regular', fontSize: 30, lineHeight: 34, color: '#f9f4ed', marginBottom: 6 },
  subtitle: { fontFamily: 'Figtree_400Regular', fontSize: 14, color: 'rgba(249,244,237,.62)', marginBottom: 18 },
  form: { gap: 12 },
  row: { flexDirection: 'row', gap: 10 },
  half: { flex: 1 },
  label: { fontFamily: 'Figtree_700Bold', fontSize: 11.5, letterSpacing: 1, textTransform: 'uppercase', color: 'rgba(249,244,237,.5)', marginBottom: 6, marginLeft: 16 },
  input: {
    height: 54,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(249,244,237,.16)',
    backgroundColor: '#1f1e24',
    color: '#f9f4ed',
    fontFamily: 'Figtree_400Regular',
    fontSize: 15,
    paddingHorizontal: 20,
  },
  passwordWrap: { justifyContent: 'center' },
  passwordInput: { paddingRight: 54 },
  eyeButton: { position: 'absolute', right: 6, height: 44, width: 44, alignItems: 'center', justifyContent: 'center' },
  error: { fontFamily: 'Figtree_600SemiBold', fontSize: 12.5, color: '#f6a06b', marginLeft: 18 },
  submitButton: {
    marginTop: 6,
    height: 56,
    borderRadius: 999,
    backgroundColor: '#c67139',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  submitButtonPressed: { backgroundColor: '#b2622d' },
  submitButtonText: { fontFamily: 'Caprasimo_400Regular', fontSize: 17, color: '#fff9f2' },
  doneWrap: { alignItems: 'center', gap: 14, paddingVertical: 32 },
  doneIcon: { width: 64, height: 64, borderRadius: 999, backgroundColor: '#7a8a5e', alignItems: 'center', justifyContent: 'center' },
  doneTitle: { fontFamily: 'Caprasimo_400Regular', fontSize: 21, color: '#f9f4ed' },
  doneSubtitle: { fontFamily: 'Figtree_400Regular', fontSize: 13.5, color: 'rgba(249,244,237,.6)' },
  footer: { alignItems: 'center', gap: 12, marginTop: 20 },
  footerLink: { fontFamily: 'Figtree_600SemiBold', fontSize: 13.5, color: 'rgba(249,244,237,.7)' },
  footerText: { fontFamily: 'Figtree_400Regular', fontSize: 13.5, color: 'rgba(249,244,237,.55)' },
  footerLinkAccent: { fontFamily: 'Figtree_700Bold', color: '#f6a06b' },
  checkboxRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  checkbox: { width: 18, height: 18, borderRadius: 4, borderWidth: 1.5, marginTop: 2, borderColor: 'rgba(249,244,237,.3)' },
  checkboxChecked: { backgroundColor: '#c67139', borderColor: '#c67139' },
  checkboxLabel: { flex: 1, fontFamily: 'Figtree_400Regular', fontSize: 13, color: 'rgba(249,244,237,.6)', lineHeight: 18 },
  checkboxLink: { fontFamily: 'Figtree_600SemiBold', color: '#f6a06b' },
});
