import { StyleSheet } from 'react-native';

/** Shared light styling for the login/register screens (Claude Design variant "2c"). */
export const authStyles = StyleSheet.create({
  screen: { backgroundColor: '#f5ead8' },
  scroll: { flexGrow: 1, paddingBottom: 40 },
  card: {
    marginHorizontal: 18,
    marginTop: -58,
    backgroundColor: '#fffdf8',
    borderRadius: 28,
    padding: 24,
    shadowColor: '#2e2b25',
    shadowOpacity: 0.22,
    shadowRadius: 32,
    shadowOffset: { width: 0, height: 12 },
    elevation: 6,
  },
  form: { gap: 12 },
  row: { flexDirection: 'row', gap: 10 },
  half: { flex: 1 },
  input: {
    height: 52,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#dcd3c4',
    backgroundColor: '#f9f4ed',
    color: '#201e1d',
    fontFamily: 'Figtree_400Regular',
    fontSize: 15,
    paddingHorizontal: 20,
  },
  passwordWrap: { justifyContent: 'center' },
  passwordInput: { paddingRight: 54 },
  eyeButton: { position: 'absolute', right: 4, height: 44, width: 44, alignItems: 'center', justifyContent: 'center' },
  error: { fontFamily: 'Figtree_600SemiBold', fontSize: 12.5, color: '#8c491a', marginLeft: 18 },
  submitButton: {
    marginTop: 2,
    height: 56,
    borderRadius: 999,
    backgroundColor: '#c67139',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  submitButtonPressed: { backgroundColor: '#b2622d' },
  submitButtonText: { fontFamily: 'Caprasimo_400Regular', fontSize: 17, color: '#fff9f2' },
  doneWrap: { flexDirection: 'row', alignItems: 'center', gap: 14, paddingVertical: 8 },
  doneIcon: { width: 48, height: 48, borderRadius: 999, backgroundColor: '#7a8a5e', alignItems: 'center', justifyContent: 'center' },
  doneTitle: { fontFamily: 'Caprasimo_400Regular', fontSize: 19, color: '#201e1d' },
  doneSubtitle: { fontFamily: 'Figtree_400Regular', fontSize: 13, color: 'rgba(32,30,29,.6)' },
  footer: { alignItems: 'center', gap: 8, marginTop: 16 },
  footerLink: { fontFamily: 'Figtree_600SemiBold', fontSize: 13.5, color: '#8c491a' },
  footerText: { fontFamily: 'Figtree_400Regular', fontSize: 13.5, color: 'rgba(32,30,29,.6)' },
  footerTextSmall: { fontFamily: 'Figtree_400Regular', fontSize: 12, color: 'rgba(32,30,29,.5)' },
  footerLinkAccent: { fontFamily: 'Figtree_700Bold', color: '#8c491a' },
  checkboxRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  checkbox: { width: 18, height: 18, borderRadius: 4, borderWidth: 1.5, marginTop: 2, borderColor: '#dcd3c4' },
  checkboxChecked: { backgroundColor: '#c67139', borderColor: '#c67139' },
  checkboxLabel: { flex: 1, fontFamily: 'Figtree_400Regular', fontSize: 13, color: 'rgba(32,30,29,.6)', lineHeight: 18 },
  checkboxLink: { fontFamily: 'Figtree_600SemiBold', color: '#8c491a' },
  trustRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 26, paddingTop: 22 },
  avatarStack: { flexDirection: 'row' },
  avatar: { width: 38, height: 38, borderRadius: 999, borderWidth: 2, borderColor: '#f5ead8' },
  trustText: { flex: 1, fontFamily: 'Figtree_400Regular', fontSize: 12.5, lineHeight: 17, color: 'rgba(32,30,29,.62)' },
});
